<!-- NATIONAL LEVEL FARMER ORGANIZATIONS -->
<option value="FEDERATION OF FREE FARMERS (FFF)">FEDERATION OF FREE FARMERS (FFF)</option>
<option value="ALTERNATIVE INDIGENOUS DEVELOPMENT FOUNDATION INC. (AIDFI)">ALTERNATIVE INDIGENOUS DEVELOPMENT FOUNDATION INC. (AIDFI)</option>
<option value="PHILIPPINE FARMERS ADVISORY BOARD">PHILIPPINE FARMERS ADVISORY BOARD</option>
<option value="NATIONAL CONFEDERATION OF IRRIGATORS ASSOCIATIONS">NATIONAL CONFEDERATION OF IRRIGATORS ASSOCIATIONS</option>
<option value="KILUSANG MAGBUBUKID NG PILIPINAS (KMP)">KILUSANG MAGBUBUKID NG PILIPINAS (KMP)</option>
<option value="PAKISAMA (PAMBANSANG KILUSAN NG MGA SAMAHAN NG MAGSASAKA)">PAKISAMA (PAMBANSANG KILUSAN NG MGA SAMAHAN NG MAGSASAKA)</option>
<option value="AGRI PARTYLIST ORGANIZATIONS">AGRI PARTYLIST ORGANIZATIONS</option>

<!-- CARAGA REGION — AGUSAN DEL NORTE -->
<option value="TAGBUCAYAN FARMERS MULTIPURPOSE COOPERATIVE (TAFAMCO)">TAGBUCAYAN FARMERS MULTIPURPOSE COOPERATIVE (TAFAMCO)</option>
<option value="SUMILIHON-TAGUIBO FARMERS ASSOCIATION (SUTAFA)">SUMILIHON-TAGUIBO FARMERS ASSOCIATION (SUTAFA)</option>
<option value="CASIKLAN WHEELS FARMERS ASSOCIATION INC. (CAWFAI)">CASIKLAN WHEELS FARMERS ASSOCIATION INC. (CAWFAI)</option>
<option value="NASIDO FARMERS AGRICULTURE COOPERATIVE (NAA-CO)">NASIDO FARMERS AGRICULTURE COOPERATIVE (NAA-CO)</option>
<option value="SIMBALAN FARMERS AGRICULTURE COOPERATIVE (SIFACO)">SIMBALAN FARMERS AGRICULTURE COOPERATIVE (SIFACO)</option>
<option value="MAT-I FARMERS MULTIPURPOSE COOPERATIVE (MFMC)">MAT-I FARMERS MULTIPURPOSE COOPERATIVE (MFMC)</option>
<option value="TUNGHAI FARMERS ASSOCIATION">TUNGHAI FARMERS ASSOCIATION</option>
<option value="SITIO LAMANLIMAN AGRARIAN REFORM BENEFICIARIES ASSOCIATION">SITIO LAMANLIMAN AGRARIAN REFORM BENEFICIARIES ASSOCIATION</option>
<option value="MACAMBUCA FARMERS MULTIPURPOSE COOPERATIVE">MACAMBUCA FARMERS MULTIPURPOSE COOPERATIVE</option>

<!-- CARAGA REGION — AGUSAN DEL SUR -->
<option value="KATIPUNAN AGRICULTURAL PRODUCERS COOPERATIVE (KAPCO)">KATIPUNAN AGRICULTURAL PRODUCERS COOPERATIVE (KAPCO)</option>
<option value="FARMERS ALTERNATIVE FOR SELF-RELIABLE MULTI-PURPOSE COOPERATIVE (FASRMCO)">FARMERS ALTERNATIVE FOR SELF-RELIABLE MULTI-PURPOSE COOPERATIVE (FASRMCO)</option>
<option value="KANGYAT FARMERS MULTIPURPOSE COOPERATIVE (KFMPC)">KANGYAT FARMERS MULTIPURPOSE COOPERATIVE (KFMPC)</option>
<option value="MURITULA FARMERS AGRICULTURAL COOPERATIVE (MUFACO)">MURITULA FARMERS AGRICULTURAL COOPERATIVE (MUFACO)</option>
<option value="NEW PROSPERITY FARMERS ASSOCIATION">NEW PROSPERITY FARMERS ASSOCIATION</option>
<option value="SAN NICOLAS FARMERS DEVELOPMENT ASSOCIATION">SAN NICOLAS FARMERS DEVELOPMENT ASSOCIATION</option>
<option value="VERUELA FARMERS AGRICULTURAL COOPERATIVE (VEFACO)">VERUELA FARMERS AGRICULTURAL COOPERATIVE (VEFACO)</option>
<option value="TRINIDAD FARMERS MULTIPURPOSE COOPERATIVE">TRINIDAD FARMERS MULTIPURPOSE COOPERATIVE</option>
<option value="BAUNGON ORGANIC FARMERS ASSOCIATION">BAUNGON ORGANIC FARMERS ASSOCIATION</option>

<!-- CARAGA REGION — SURIGAO DEL NORTE -->
<option value="SAN ISIDRO VEGETABLE GROWERS ASSOCIATION">SAN ISIDRO VEGETABLE GROWERS ASSOCIATION</option>
<option value="DAPA COCONUT FARMERS ASSOCIATION">DAPA COCONUT FARMERS ASSOCIATION</option>
<option value="BUKAS FARMERS ASSOCIATION">BUKAS FARMERS ASSOCIATION</option>
<option value="CAUB SMALL FARMERS FISHERFOLK ASSOCIATION">CAUB SMALL FARMERS FISHERFOLK ASSOCIATION</option>
<option value="MAPUPA FARMERS ASSOCIATION">MAPUPA FARMERS ASSOCIATION</option>
<option value="GENERAL LUNA AGRI-FARMERS ASSOCIATION">GENERAL LUNA AGRI-FARMERS ASSOCIATION</option>

<!-- CARAGA REGION — SURIGAO DEL SUR -->
<option value="TAGO FARMERS MULTIPURPOSE COOPERATIVE">TAGO FARMERS MULTIPURPOSE COOPERATIVE</option>
<option value="CANTILAN ORGANIC FARMERS ASSOCIATION">CANTILAN ORGANIC FARMERS ASSOCIATION</option>
<option value="LIANGA FARMERS AGRICULTURAL COOPERATIVE">LIANGA FARMERS AGRICULTURAL COOPERATIVE</option>
<option value="LANUZA AGRI-PRODUCERS COOPERATIVE">LANUZA AGRI-PRODUCERS COOPERATIVE</option>
<option value="BRGY SAN ROQUE FARMERS ASSOCIATION">BRGY SAN ROQUE FARMERS ASSOCIATION</option>
<option value="HINATUAN VEGETABLE FARMERS GROUP">HINATUAN VEGETABLE FARMERS GROUP</option>

<!-- CARAGA REGION — DINAGAT ISLANDS -->
<option value="BASILISA VEGETABLE FARMERS ASSOCIATION">BASILISA VEGETABLE FARMERS ASSOCIATION</option>
<option value="DINAGAT FARMERS COOPERATIVE">DINAGAT FARMERS COOPERATIVE</option>
<option value="LIBJO FARMERS MULTIPURPOSE COOPERATIVE">LIBJO FARMERS MULTIPURPOSE COOPERATIVE</option>
<option value="LARES FARMERS AGRARIAN REFORM BENEFICIARIES ASSOCIATION">LARES FARMERS AGRARIAN REFORM BENEFICIARIES ASSOCIATION</option>
<option value="SAN JOSE AGRI-FISHERY FARMERS ASSOCIATION">SAN JOSE AGRI-FISHERY FARMERS ASSOCIATION</option>

<!-- EXTRA FARMER + AGRI GROUPS -->
<option value="MALAYBALAY HIGHLAND FARMERS ASSOCIATION">MALAYBALAY HIGHLAND FARMERS ASSOCIATION</option>
<option value="NORTHERN MINDANAO ORGANIC FARMERS FEDERATION">NORTHERN MINDANAO ORGANIC FARMERS FEDERATION</option>
<option value="SOUTHERN PHILIPPINES CORN FARMERS FEDERATION">SOUTHERN PHILIPPINES CORN FARMERS FEDERATION</option>
<option value="UNITED PALAY FARMERS ASSOCIATION">UNITED PALAY FARMERS ASSOCIATION</option>
<option value="UNITED VEGETABLE GROWERS ASSOCIATION">UNITED VEGETABLE GROWERS ASSOCIATION</option>
<option value="COCONUT FARMERS OF MINDANAO FEDERATION">COCONUT FARMERS OF MINDANAO FEDERATION</option>
<option value="BANANA GROWERS FEDERATION OF MINDANAO">BANANA GROWERS FEDERATION OF MINDANAO</option>
<option value="RICE FARMERS UNITED COOPERATIVE">RICE FARMERS UNITED COOPERATIVE</option>
<option value="HIGHLAND AGRI FARMERS COOPERATIVE">HIGHLAND AGRI FARMERS COOPERATIVE</option>
<option value="SUSTAINABLE ORGANIC FARMERS ALLIANCE">SUSTAINABLE ORGANIC FARMERS ALLIANCE</option>